### ISSUE TITLE
404 Error when looking at AWS Cloud Practitioner notes

### ISSUE THREAD

**Issue by ewalker101** [rishabkumar7/CloudNotes#6]
Hello, I hope you are well. It seems that your AWS Cloud Practitioner notes are missing. I get an Error 404 while trying to access them.

**Comment by rishabkumar7** [comment]
hey @ewalker101 thanks for the issue, I have updated the README to reflect correct links, also there is a website for my notes which is maintened on a regular basis - https://rishabkumar.com/notes
